#!/usr/bin/env python3
"""Deterministic SVG figures derived only from packaged frozen result data."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; MEDIA=ROOT/"media"; MEDIA.mkdir(exist_ok=True)
GEN=ROOT/"experiments/gen-design-001/data"; NUM=ROOT/"experiments/num-synth-001/data/results_summary.json"
W,H=1000,560
def svg(body,title): return f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}"><style>text{{font-family:Arial,sans-serif;fill:#172033}}.title{{font-size:26px;font-weight:700}}.sub{{font-size:15px;fill:#52627a}}.label{{font-size:16px;font-weight:600}}.note{{font-size:13px;fill:#52627a}}</style><rect width="100%" height="100%" fill="#f8fafc"/>{body}</svg>'
def save(name,body,title): (MEDIA/name).write_text(svg(body,title))
def truss(name,x,y,w=430,h=205):
    d=json.loads((GEN/(name+'.json')).read_text()); pts=[(x+(i%6)*w/5,y+(i//6)*h) for i in range(12)]; parts=[]
    for (a,b),area in zip(d['members'],d['areas']):
        x1,y1=pts[a];x2,y2=pts[b]; parts.append(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#2563eb" stroke-width="{2+area*7}"/>')
    parts += [f'<circle cx="{px}" cy="{py}" r="4" fill="#172033"/>' for px,py in pts]
    return ''.join(parts)
def main():
    r=json.loads((GEN/'results_summary.json').read_text()); n=json.loads(NUM.read_text())
    save('gen-design-topologies.svg',f'<text x="50" y="48" class="title">GEN-DESIGN-001 topology comparison</text><text x="50" y="76" class="sub">Synthetic normalized truss experiment — member width shows frozen normalized area, not a build recommendation.</text><text x="50" y="120" class="label">B2_warren conventional baseline</text>{truss("B2_warren",50,170)}<text x="530" y="120" class="label">G06 generated topology</text>{truss("G06",530,170)}<text x="50" y="470" class="note">Design-load mass: B2 6.069109; G06 4.535164. Layout is a fixed synthetic lattice.</text>', 'topologies')
    b2,g06=r['design_masses']['B2_warren'],r['design_masses']['G06']; maxv=7
    save('gen-design-mass-and-held-out.svg',f'<text x="50" y="48" class="title">Apparent design win, then held-out failure</text><text x="50" y="78" class="sub">Synthetic normalized truss experiment. Stress utilization must be at or below 1.0.</text><text x="60" y="128" class="label">Design-load mass</text><rect x="60" y="160" width="{b2/maxv*360}" height="42" fill="#94a3b8"/><text x="70" y="188" class="label">B2_warren 6.069109</text><rect x="60" y="220" width="{g06/maxv*360}" height="42" fill="#2563eb"/><text x="70" y="248" class="label">G06 4.535164</text><text x="60" y="300" class="label">G06: 25.27% lighter on frozen DESIGN loads</text><text x="530" y="128" class="label">Held-out stress utilization</text><line x1="530" y1="350" x2="940" y2="350" stroke="#dc2626" stroke-width="3"/><text x="945" y="355" class="note">limit 1.0</text><rect x="580" y="350" width="80" height="{r["held_out"]["G06"]["H_edge_down"]*14}" transform="translate(0,-{r["held_out"]["G06"]["H_edge_down"]*14})" fill="#dc2626"/><text x="560" y="160" class="label">G06 / H_edge_down</text><text x="570" y="190" class="title">12.5×</text><text x="530" y="430" class="label">Held-out edge load invalidates robust-superiority claim.</text><text x="530" y="458" class="note">Every baseline and finalist failed at least one held-out stress constraint.</text>', 'mass heldout')
    labels=list(r['held_out']['G06']); vals=[r['held_out']['G06'][x] for x in labels]; bars=''.join(f'<rect x="{90+i*260}" y="390" width="100" height="{-v*22}" fill="{"#dc2626" if v>1 else "#16a34a"}"/><text x="{75+i*260}" y="425" class="note">{name}</text><text x="{105+i*260}" y="375" class="label">{v:.2f}</text>' for i,(name,v) in enumerate(zip(labels,vals)))
    save('gen-design-stress-utilization.svg',f'<text x="50" y="48" class="title">G06 held-out stress utilization</text><text x="50" y="76" class="sub">Ratios above 1.0 violate the frozen stress constraint. Equilibrium residuals remained near numerical precision.</text><line x1="60" y1="368" x2="900" y2="368" stroke="#dc2626" stroke-width="3"/><text x="905" y="373" class="note">1.0 limit</text>{bars}<text x="50" y="500" class="note">This evaluates a synthetic normalized truss model only; it does not describe a physical structure.</text>', 'stress')
    save('num-synth-summary.svg',f'<text x="50" y="48" class="title">NUM-SYNTH-001 solver evidence summary</text><rect x="50" y="65" width="900" height="42" rx="6" fill="#fef3c7"/><text x="70" y="92" class="label">HISTORICAL TIMING RECORD — NOT A ROBUST BENCHMARK</text><text x="50" y="150" class="label">Public reproduction: five recorded cases × two solvers</text><rect x="50" y="180" width="500" height="28" fill="#2563eb"/><text x="60" y="201" fill="white" class="label">Numerical validity replay</text><text x="50" y="270" class="label">Historical record: 25 valid solver-result rows</text><text x="50" y="300" class="note">Process-recorded only; held-out secrecy is not cryptographically proven.</text><text x="50" y="370" class="label">Adversarial over-relaxed Jacobi control: 8 / 8 design cases invalid</text><rect x="50" y="395" width="500" height="28" fill="#dc2626"/><text x="60" y="416" fill="white" class="label">8 failures</text><text x="50" y="480" class="note">Historical timing aggregates and a new transparent timing sample are in experiment evidence.</text>', 'num')
if __name__=='__main__': main()
